### ISSUE TITLE
After JAMF and/or Bit9 installation, computer restarts itself upon closing 

### ISSUE THREAD

**Issue by annahsgraves** [GSA/laptop-management#43]
Every time I lock and close my computer, my computer shuts down and restarts. Until this week, this problem did not exist, which leads me to believe this is linked to the Bit9 installation.

**Comment by jacobian** [comment]
#41 is (I think) the same issue.

**Comment by annahsgraves** [comment]
Yes it is @jacobian! I'll close this one and post over there. Thanks for flagging!
