### ISSUE TITLE
After Bit9 installation, major Chrome crashing problems

### ISSUE THREAD

**Issue by annahsgraves** [GSA/laptop-management#44]
Upon getting onto my computer on 12/11/17 (the Monday after Bit9 installation), Chrome completely crapped out on me. It repeatedly crashed, wouldn't open for more than half a second, wouldn't allow me to restore old windows, etc. I imported my chrome bookmarks and history into Safari so that I could work there, but it was enormously disruptive and mentally taxing to deal with this while doing project work. I received no assistance from the help desk, every link I tried to get to from Slack opened a chrome link since chrome was my default browser and this crashed chrome and made my computer freak out. None of my plug-ins in chrome exist in Safari, so for every video or tool I tried to use, I had to go through an install process. Google calendar's scheduling assistant wasn't working in Safari which meant I had to take extra steps every time I needed to schedule something. 

On the first conversation I had with the help desk, I was basically told "too bad, you'll just have to wait." I got a call back over 5 hours later and spent over 10 minutes on the phone with somebody and was late to a meeting because I had to explain who I am and how TTS macs are set up and the fact that I'm remote but not regularly VPNed in. I got no positive outcomes.

When I was able to get attention to this problem in slack, Ian Bell helped me completely remove Chrome from my computer and reinstall. This took less than 20 minutes. I lost all of my bookmarks and history and thankfully was able to import my bookmarks back into chrome from safari.

**Comment by konklone** [comment]
Closing this in favor of #41, and posting the comment there.
